version: 0.0
os: linux

files:
  - source: server/
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: server/scripts/cleanup.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: server/scripts/install_dependencies.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: server/scripts/start_server.sh
      timeout: 60
      runas: ec2-user
